apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    task: monitoring
    k8s-app: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      nodeSelector:
        node: master
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
      #   volumeMounts:
      #   - name: influxdb-storage
      #     mountPath: "/data"
      #     subPath: kubernetes/influxdb
      # volumes:
      # - name: influxdb-storage
      #   persistentVolumeClaim:
      #     claimName: nfs-kube-system
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/config.toml
          name: config
          subPath: config.toml
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: config
        configMap:
          name: influxdb-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    name: http-influx
    protocol: TCP
    nodePort: 31069
  - port: 8089
    targetPort: 8089
    name: udp-influx   
    protocol: UDP
    nodePort: 31089 
  selector:
    k8s-app: influxdb
    task: monitoring

